version: "3"

networks:
  vemta-backend:
    external: true

services:

  mysql:
    image: mysql:5.7
    restart: always
    networks:
      - vemta-backend
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: vemta
    volumes:
      - ./sql/schema.sql:/docker-entrypoint-initdb.d/0_init.sql
    ports:
      - "3307:3306"

  mvc:
    build: .
    container_name: vemta-mvc-application
    networks:
      - vemta-backend
    volumes:
      - .:/go/src
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
    ports:
      - "8081:8081"
      - "3333:3333"

  zookeeper:
    image: confluentinc/cp-zookeeper:7.3.0
    hostname: zookeeper
    container_name: zookeeper
    networks:
      - vemta-backend
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-server:7.3.0
    hostname: broker
    container_name: broker
    depends_on:
      - zookeeper
    networks:
      - vemta-backend
    ports:
      - "9092:9092"
      - "9094:9094"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092,OUTSIDE://host.docker.internal:9094
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      CONFLUENT_METRICS_ENABLE: 'false'
      CONFLUENT_SUPPORT_CUSTOMER_ID: 'anonymous'

  control-center:
    networks:
      - vemta-backend
    image: confluentinc/cp-enterprise-control-center:7.3.0
    hostname: control-center
    container_name: control-center
    depends_on:
      - broker
    ports:
      - "9021:9021"
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: 'broker:29092'
      CONTROL_CENTER_REPLICATION_FACTOR: 1
      CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
      CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
      CONFLUENT_METRICS_TOPIC_REPLICATION: 1
      PORT: 9021

  kafka-topics-generator:
    networks:
      - vemta-backend
    image: confluentinc/cp-server:7.3.0
    depends_on:
      - broker
    command: >
      bash -c
        "sleep 10s &&
        kafka-topics --create --topic=createPlugin --if-not-exists --bootstrap-server=broker:29092 &&
        kafka-topics --create --topic=createUser --if-not-exists --bootstrap-server=broker:29092" &&
        kafka-topics --create --topic=createRelease --if-not-exists --bootstrap-server=broker:29092"