// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0

package db

import (
	"time"
)

type VmtItem struct {
	ID          string    `json:"id"`
	Title       string    `json:"title"`
	Description string    `json:"description"`
	Isgood      bool      `json:"isgood"`
	Createdat   time.Time `json:"createdat"`
}

type VmtOrder struct {
	ID                 string  `json:"id"`
	Customer           string  `json:"customer"`
	Price              float64 `json:"price"`
	Paymentmethod      int32   `json:"paymentmethod"`
	Status             int32   `json:"status"`
	Discountraw        float64 `json:"discountraw"`
	Discountpercentual float64 `json:"discountpercentual"`
}

type VmtOrderdetail struct {
	Orderid  string `json:"orderid"`
	Item     string `json:"item"`
	Quantity int32  `json:"quantity"`
}

type VmtUser struct {
	Email     string    `json:"email"`
	Fullname  string    `json:"fullname"`
	Birthdate time.Time `json:"birthdate"`
}
